services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    env_file:
      - .env.local
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGOUSER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGOPASSWORD}"
      MONGO_INITDB_DATABASE: "${MONGODB}"
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: local
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env.local
      - .env.local
    ports:
      - "3002:3002"
    depends_on:
      - postgres
      - mongodb
    volumes:
      - ./backend:/app
    environment:
      FLASK_APP: app.py
      FLASK_RUN_PORT: 3002
      FLASK_DEBUG: 1

volumes:
  postgres_data:
  mongodb_data: 